# Numpy
1) Numpy is **numerical Python**, a open source Python library.
2) It contains **multidimensional array (ndarray), homogenous (same-type)** data structures.
3) It also contains large number of functions that operate efficiently on these data structures.

# 1. How to import Numpy.

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [3]:
np.__version__

'1.26.4'

1) 1-D array is like list 

    eg. [1,23,5,7]
    
2) 2-D array is like matrix 

    eg. [[1,2,3],
         [4,5,6],
         [7,8,9]]
         
3) 3-D array is like set of tables.

4) class of numpy array is **ndarray**.

5) Restrictions on most of numpy arrays.
    5.1) All elements of the array should be of the same type.
    5.2) Once created, size of the array can't be change.
    5.3) shape of the array must be rectangle, not jagged eg. every row of a two dimensional array must have same number of elements.
    



# 2. Numpy array fundamentals

## 2.1 intializing the np.array using python sequence such as list.


In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

## 2.2 Accessing the elements using index

In [6]:
a[0]

1

**Note:-** Numpy array are mutable.

In [7]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

## 2.3 Slicing in numpy array 
Slicing in numpy array is different from slicing of python list :
    
    Differences:
        1) slicing in numpy array creates a **view** of the portion of the original array sliced 
        not a copy which is found in python list slicing.
        2) slicing doesn't create copy.
        3) changes made to the **view** reflects the changes in the original numpy array.
        

In [8]:
a[:3]

array([10,  2,  3])

In [10]:
b = a[3:] 
b # b is a View

array([4, 5, 6])

In [13]:
b[0] = 40 # changes in view 'b' make changes in original numpy array 'a'

In [14]:
a 

array([10,  2,  3, 40,  5,  6])

## 2.4 Higher Dimensional array can be created using nested python list

In [15]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# accessing element in multidimensional array
# a[axis or row, index in that axis or column ]

# accessing element 8 present in row 1 and column 3
c[1,3]

8

 [**Note:-**] A better mental model is to think of the **column index** as coming to the ***last*** and the **row index** as ***second to last*** 

# 3. Numpy array attributes
1) ndim
2) shape
3) size
4) dtype

[1.] **ndim** --> number of dimensions of an array.

In [17]:
c.ndim

2

[2.] **shape** --> shape of an array is a tuple of non-negative integers that specify number of elements along each dimensions

In [19]:
c.shape

(3, 4)

[3.] **size** --> total number of elements in an array.

In [20]:
c.size

12

[4.] **dtype** --> records the data type

In [21]:
c.dtype

dtype('int64')

# 4. Basic Numpy arrays
1) np.zeros()
2) np.ones()
3) np.empty()
4) np.arange()
5) np.linspace()

**np.zeros()**

In [22]:
# [1.] Create array of 0's
z = np.zeros(2)
z

array([0., 0.])

In [26]:
print(type(z))

<class 'numpy.ndarray'>


In [27]:
print(z.ndim)

1


In [28]:
print(z.shape)

(2,)


In [29]:
print(z.size)

2


In [30]:
print(z.dtype)

float64


**np.ones()**

In [31]:
o = np.ones(3)
o

array([1., 1., 1.])

**np.empty()** --> creates an array whose intial content is random and depends on the state of the memory.

In [32]:
e = np.empty(2)
e

array([0., 0.])

**np.arange()** --> creates an array with a range of elements

In [35]:
r = np.arange(4)
r

array([0, 1, 2, 3])

**np.arange(start, last, step_size)**

In [36]:
arr = np.arange(2, 9, 2)
arr

array([2, 4, 6, 8])

**np.linspace()** --> to create an array with values that are spaced linearly in a specified interval.

In [39]:
ls = np.linspace(0, 10, num=5) # here 'num' parameter is for number of samples to generate.
ls

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [41]:
ls2 = np.linspace(0,10, num=4)
ls2

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

**Note:-** We can use **dtype** to specify the type of data to use while creating an array

In [42]:
one = np.ones(4, dtype='int64')
one

array([1, 1, 1, 1])

In [43]:
ones = np.ones(5, dtype=np.int64)
ones

array([1, 1, 1, 1, 1])

# Adding, removing, and sorting elements
1) np.sort() => can also specify **axis, kind, and order** when calling the function. Returns sorted copy of an array.


2) np.concatenate() => used to concatenate arrays.

In [2]:
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(a)

[2 1 5 3 7 4 6 8]


In [3]:
# sorting in ascending order.
a_sorted = np.sort(a)
print(a_sorted)

[1 2 3 4 5 6 7 8]


**argsort** => which is an indirect sort along a specified axis,

**lexsort** => which is an indirect stable sort on multiple keys,

**searchsorted** => which will find elements in a sorted array, 

**partition** => which is a partial sort.

In [4]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [5]:
concatenated_arrys = np.concatenate((x,y))
print(concatenated_arrys)

[1 2 3 4 5 6 7 8]


In [7]:
v1 = np.array([[1,2],[3,4]])
v2 = np.array([[5, 6]])

v_prime = np.concatenate((v1,v2), axis=0)
print(v_prime)
print()
print(f'shape: {v_prime.shape}')

[[1 2]
 [3 4]
 [5 6]]

shape: (3, 2)
