# Numpy
1) Numpy is **numerical Python**, a open source Python library.
2) It contains **multidimensional array (ndarray), homogenous (same-type)** data structures.
3) It also contains large number of functions that operate efficiently on these data structures.

# 1. How to import Numpy.

In [2]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [3]:
np.__version__

'1.26.4'

1) 1-D array is like list 

    eg. [1,23,5,7]
    
2) 2-D array is like matrix 

    eg. [[1,2,3],
         [4,5,6],
         [7,8,9]]
         
3) 3-D array is like set of tables.

4) class of numpy array is **ndarray**.

5) Restrictions on most of numpy arrays.
    5.1) All elements of the array should be of the same type.
    5.2) Once created, size of the array can't be change.
    5.3) shape of the array must be rectangle, not jagged eg. every row of a two dimensional array must have same number of elements.
    



# 2. Numpy array fundamentals

## 2.1 intializing the np.array using python sequence such as list.


In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

## 2.2 Accessing the elements using index

In [6]:
a[0]

1

**Note:-** Numpy array are mutable.

In [7]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

## 2.3 Slicing in numpy array 
Slicing in numpy array is different from slicing of python list :
    
    Differences:
        1) slicing in numpy array creates a **view** of the portion of the original array sliced 
        not a copy which is found in python list slicing.
        2) slicing doesn't create copy.
        3) changes made to the **view** reflects the changes in the original numpy array.
        

In [8]:
a[:3]

array([10,  2,  3])

In [10]:
b = a[3:] 
b # b is a View

array([4, 5, 6])

In [13]:
b[0] = 40 # changes in view 'b' make changes in original numpy array 'a'

In [14]:
a 

array([10,  2,  3, 40,  5,  6])

## 2.4 Higher Dimensional array can be created using nested python list

In [15]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# accessing element in multidimensional array
# a[axis or row, index in that axis or column ]

# accessing element 8 present in row 1 and column 3
c[1,3]

8

 [**Note:-**] A better mental model is to think of the **column index** as coming to the ***last*** and the **row index** as ***second to last*** 

# 3. Numpy array attributes
1) ndim
2) shape
3) size
4) dtype

[1.] **ndim** --> number of dimensions of an array.

In [17]:
c.ndim

2

[2.] **shape** --> shape of an array is a tuple of non-negative integers that specify number of elements along each dimensions

In [19]:
c.shape

(3, 4)

[3.] **size** --> total number of elements in an array.

In [20]:
c.size

12

[4.] **dtype** --> records the data type

In [21]:
c.dtype

dtype('int64')

# 4. Basic Numpy arrays
1) np.zeros()
2) np.ones()
3) np.empty()
4) np.arange()
5) np.linspace()

**np.zeros()**

In [22]:
# [1.] Create array of 0's
z = np.zeros(2)
z

array([0., 0.])

In [26]:
print(type(z))

<class 'numpy.ndarray'>


In [27]:
print(z.ndim)

1


In [28]:
print(z.shape)

(2,)


In [29]:
print(z.size)

2


In [30]:
print(z.dtype)

float64


**np.ones()**

In [31]:
o = np.ones(3)
o

array([1., 1., 1.])

**np.empty()** --> creates an array whose intial content is random and depends on the state of the memory.

In [32]:
e = np.empty(2)
e

array([0., 0.])

**np.arange()** --> creates an array with a range of elements

In [35]:
r = np.arange(4)
r

array([0, 1, 2, 3])

**np.arange(start, last, step_size)**

In [36]:
arr = np.arange(2, 9, 2)
arr

array([2, 4, 6, 8])

**np.linspace()** --> to create an array with values that are spaced linearly in a specified interval.

In [39]:
ls = np.linspace(0, 10, num=5) # here 'num' parameter is for number of samples to generate.
ls

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [41]:
ls2 = np.linspace(0,10, num=4)
ls2

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

**Note:-** We can use **dtype** to specify the type of data to use while creating an array

In [42]:
one = np.ones(4, dtype='int64')
one

array([1, 1, 1, 1])

In [43]:
ones = np.ones(5, dtype=np.int64)
ones

array([1, 1, 1, 1, 1])

# Adding, removing, and sorting elements
1) np.sort() => can also specify **axis, kind, and order** when calling the function. Returns sorted copy of an array.


2) np.concatenate() => used to concatenate arrays.

In [2]:
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(a)

[2 1 5 3 7 4 6 8]


In [3]:
# sorting in ascending order.
a_sorted = np.sort(a)
print(a_sorted)

[1 2 3 4 5 6 7 8]


**argsort** => which is an indirect sort along a specified axis,

**lexsort** => which is an indirect stable sort on multiple keys,

**searchsorted** => which will find elements in a sorted array, 

**partition** => which is a partial sort.

In [4]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [5]:
concatenated_arrys = np.concatenate((x,y))
print(concatenated_arrys)

[1 2 3 4 5 6 7 8]


In [7]:
v1 = np.array([[1,2],[3,4]])
v2 = np.array([[5, 6]])

v_prime = np.concatenate((v1,v2), axis=0)
print(v_prime)
print()
print(f'shape: {v_prime.shape}')

[[1 2]
 [3 4]
 [5 6]]

shape: (3, 2)


# Shape and size of an numpy array
1) **ndarray.ndim** => tells number of axes or dimensions of the array.
2) **ndarray.shape** => returns a tuple of non-negative integers that tells number of elements present along each dimension of the array.
3) **ndarray.size** => tells total number of elements present in the array.

In [3]:
arr = np.array([[[0, 1, 2, 3],
                 [4, 5, 6, 7]],
                [[0, 1, 2, 3],
                 [4, 5, 6, 7]],
                [[0 ,1 ,2, 3],
                 [4, 5, 6, 7]]])

In [4]:
arr.ndim

3

In [5]:
arr.shape

(3, 2, 4)

In [6]:
arr.size

24

# Reshaping an array possible ?
==> **YES** using **reshape()** function

In [7]:
v4 = np.arange(10)
v4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
v5 = v4.reshape(5,2)
v5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Adding new axis to an array.

**np.newaxis** => increases the dimension of your array by one dimension when used once.
1D array => 2D array or 2D array => 3D array.

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [3]:
a2 = a[np.newaxis, :]

In [4]:
a2.shape

(1, 6)

In [5]:
row_vector = a[np.newaxis, :]

In [6]:
row_vector.shape

(1, 6)

In [7]:
col_vector = a[:, np.newaxis]

In [8]:
col_vector.shape

(6, 1)

**np.expand_dims** => used to expand the dimensions of an array by inserting new axis at a specified index position.

In [9]:
brr = np.arange(1,10)
brr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
brr.shape

(9,)

In [11]:
# add an axis at index position 1
brr1 = np.expand_dims(brr, axis=1)
brr1.shape

(9, 1)

In [12]:
brr1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
# add an axis at index position 0
brr2 = np.expand_dims(brr, axis=0)
brr2.shape

(1, 9)

In [14]:
brr2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Indexing and slicing

In [2]:
a = np.array([1,2,3])

In [3]:
a[1]

2

In [4]:
a[:2]

array([1, 2])

In [5]:
a[1:]

array([2, 3])

In [7]:
a[-3]

1

In [8]:
a[-3:]

array([1, 2, 3])

In [9]:
a[:-1]

array([1, 2])

In [10]:
# slicing in more dimensional array
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
b[1]

array([5, 6, 7, 8])

In [12]:
b[1,2] # gets the number 7 which is on 2 index in axis 1

7

In [14]:
# to get 11
b[2, 2]

11

**Custom filtering**

In [16]:
# to get all values below 8
below_eight = b < 8
print(b[below_eight])

[1 2 3 4 5 6 7]


In [17]:
# get number equal to or greater than 5
five_up = b >= 5
print(b[five_up])

[ 5  6  7  8  9 10 11 12]


In [18]:
# get elements divisible by 2
divisible_by_2 = b[b%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

***Note:-** to combine 2 or more conditions use **&** and **|**

In [20]:
# get numbers greater than 2 but less than or equal 11
required_numbers = b[(b > 2) & (b <= 11)]
required_numbers

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

**Note:-** **&** and **|** can also be used to get boolean arrays

In [22]:
# get an array of boolean values that satisfy the following conditions are values greater than or equal to 5?
five_up_bool = (b > 5) | (b == 5)
print(five_up_bool)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


**Note:-** **np.nonzero()** can be used to select elements or indices from an array.

In [24]:
# get the indices of the elements of b that are less than 5
c = np.nonzero(b < 5)
c

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

1) Returns the output as tuple of arrays: one for each dimension. 
2) Here, first array represents the row indices where the value is found 
and the second array represents the columns indices where the value is found.

In [26]:
# printing the above selected elements
print(b[c])

[1 2 3 4]


**Note:-** if the value is not present then it will give an empty array

# Creating array from an existing data
1) Slicing and indexing
2) np.vstack()
3) np.hstack()
4) np.hsplit()
5) .view()
6) copy()

In [27]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# new array from section of existing array
a1 = a[3:9]
a1 

array([4, 5, 6, 7, 8, 9])

In [30]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

**Vertical Stacking**

In [31]:
v_a1_a2 = np.vstack((a1, a2))
v_a1_a2

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

**Horizontal Stacking**

In [32]:
h_a1_a2 = np.hstack((a1,a2))
h_a1_a2

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

**Note:-** Order of passing the array for stacking matters.

In [33]:
h_a2_a1 = np.hstack((a2, a1))
h_a2_a1

array([[3, 3, 1, 1],
       [4, 4, 2, 2]])

1) We can split an existing array using **np.hsplit()**.
2) We can specify number of equally shaped arrays to return.
3) Or we can specify the ***columns*** after which division should occur.

In [34]:
x = np.arange(1,25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

equally shaped arrays.

In [35]:
e_x = np.hsplit(x, 3)
e_x

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

divison by columns

In [38]:
# get division from 3 and 4 column
d_x = np.hsplit(x, (3, 4))
d_x

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

**.view()** method gives a shallow copy of the data

slicing and indexing also returns a **view** of the original data.

In [39]:
v = np.arange(1,13)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
z = v.view()
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
# or simply
y = v
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
# change 4 at index 3 using z
print(z[3])
z[3] = 44
print(z)

4
[ 1  2  3 44  5  6  7  8  9 10 11 12]


In [43]:
# now print original vector v
v

array([ 1,  2,  3, 44,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
# change 9 at index 8 using y
print(y[8])
y[8] = 99
y

9


array([ 1,  2,  3, 44,  5,  6,  7,  8, 99, 10, 11, 12])

In [45]:
# now print original vector v
v

array([ 1,  2,  3, 44,  5,  6,  7,  8, 99, 10, 11, 12])

**.copy()** method returns a deep copy of the data

In [46]:
v1 = np.arange(1,15)
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
v1_cp = v1.copy()
v1_cp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
# change value 4 at index 3 in v1_cp
print(v1_cp[3])
v1_cp[3] = 44
v1_cp

4


array([ 1,  2,  3, 44,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
# now print the original vector v1
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Basic array operations
1) addition
2) subtraction
3) multiplication
4) division and more.

In [4]:
data = np.array([1,2])
print(data)

[1 2]


In [5]:
ones = np.ones(2, dtype=int)
print(ones)

[1 1]


In [6]:
# add 1 to data
new_data = data + ones
print(new_data)

[2 3]


In [7]:
data1 = np.array([33, 44])
print(data1)

[33 44]


In [8]:
# subtract 1 to data1
new_data1 = data1 - ones
print(new_data1)

[32 43]


In [11]:
# multiply data * data1
new_data2 = data * data1
print(new_data2)

[33 88]


In [10]:
data3 = np.array([11,11])

In [12]:
# division
new_data3 = new_data2 / data3
print(new_data3)

[3. 8.]


**sum()** -> to find sum of elements of an array.

In [13]:
arr_ele_sum = new_data3.sum()
print(arr_ele_sum)

11.0


In [14]:
mat = np.array([[1, 1], [2, 2]])
print(mat)

[[1 1]
 [2 2]]


In [15]:
# to add over the rows
row_add = mat.sum(axis=0)
row_add

array([3, 3])

In [16]:
# to add over the columns
column_add = mat.sum(axis=1)
column_add

array([2, 4])

# Broadcasting
1) Operation between an array and a single value (ie. operation between a vector and a scalar value).
2) Operation between arrays of two different sizes.

In [17]:
print(data)

[1 2]


In [18]:
# triple each element of data vector
print(triple_data := data * 3)

[3 6]


In [19]:
triple_data

array([3, 6])

# Other usefull methods are :
1) min()
2) max()
3) sum()
4) mean()
5) prod()
6) std()


In [3]:
m1 = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [4]:
m1.min()

0.05093587

In [5]:
m1.max()

0.82485143

In [6]:
m1.mean()

0.4049648666666667

In [7]:
m1.prod() # returns the product of all elements of m1

1.4517216120884712e-06

In [8]:
m1.std() # returns the standard deviation of m1

0.21392120766089617

**Note:-** Can also use aggregate functions along the specified axis

In [10]:
# calculate minimum along each column
m1.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

Above listed 4 values coresponds to the number of columns in m1 array

# Creating matrices ( 2D Array)
--> using nested list

In [11]:
mat1 = np.array([[1,2],
                [3,4],
                [5,6]])
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# accessing a single element 2 of mat1
mat1[0,1]


2

In [13]:
# slicing a portion of mat1
mat1[1:3] # means portion from row 1 to row 2 (ie. 3-1=2) and all columns

array([[3, 4],
       [5, 6]])

In [16]:
mat1[:,1] # means all rows but only column 1

array([2, 4, 6])

In [17]:
# minimum element in mat1
mat1.min()

1

In [18]:
# maximum element in mat1
mat1.max()

6

In [19]:
# mean of all element of mat1
mat1.mean()

3.5

In [21]:
# aggregate function along any axis
mat1.max(axis=1)

array([2, 4, 6])

**Note:-** Can add (+), multiply(*) arrays that have same size.

In [22]:
a1 = np.array([[1,2],
              [3,4]])
a2 = np.array([[5,6],
              [7,8]])

a1plusa2 = a1 + a2
a1plusa2

array([[ 6,  8],
       [10, 12]])

In [23]:
a1proda2 = a1 * a2
a1proda2

array([[ 5, 12],
       [21, 32]])

In [24]:
a1suba2 = a1 - a2
a1suba2

array([[-4, -4],
       [-4, -4]])

**Note:-** Arithmetic operations can be applied to different size of arrays but only if one of the array is one column array or one row array. Then Numpy will use broadcasting rules of operation.

In [26]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row # this adds the ones_row array to each row of data array.

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
# 1D arrays

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
rng = np.random.default_rng()

In [30]:
rng.random(3)

array([0.33098203, 0.5842381 , 0.72631467])

In [31]:
np.random.random(5)

array([0.54558886, 0.6375788 , 0.25671833, 0.05421478, 0.35254462])

In [32]:
# 2D arrays

In [33]:
np.ones((3,4)) # 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
d = np.random.random((3, 4))
d

array([[0.89663104, 0.29719737, 0.19135032, 0.72443301],
       [0.12892409, 0.37240776, 0.05595351, 0.71247159],
       [0.87141204, 0.49780146, 0.5356471 , 0.09803977]])

In [38]:
d.std()

0.29002494725828487

In [40]:
help(np.random.Generator)

Help on class Generator in module numpy.random._generator:

class Generator(builtins.object)
 |  Generator(bit_generator)
 |
 |  Container for the BitGenerators.
 |
 |  ``Generator`` exposes a number of methods for generating random
 |  numbers drawn from a variety of probability distributions. In addition to
 |  the distribution-specific arguments, each method takes a keyword argument
 |  `size` that defaults to ``None``. If `size` is ``None``, then a single
 |  value is generated and returned. If `size` is an integer, then a 1-D
 |  array filled with generated values is returned. If `size` is a tuple,
 |  then an array with that shape is filled and returned.
 |
 |  The function :func:`numpy.random.default_rng` will instantiate
 |  a `Generator` with numpy's default `BitGenerator`.
 |
 |  **No Compatibility Guarantee**
 |
 |  ``Generator`` does not provide a version compatibility guarantee. In
 |  particular, as better algorithms evolve the bit stream may change.
 |
 |  Parameters
 | 

In [41]:
rng1 = np.random.default_rng()

In [42]:
# random integers between 0 and 4 with the size 2 X 4
d1 = rng1.integers(5, size=(2,4))
d1

array([[1, 1, 0, 2],
       [0, 3, 4, 4]])